# Page Rank
PageRank adalah algoritma yang digunakan oleh Google Search untuk menentukan peringkat dari halaman web dalam hasil pencarian mereka. Algoritma ini dinamai sesuai dengan nama salah satu pendirinya, Larry Page, dan menjadi salah satu inovasi penting yang membuat Google menjadi mesin pencari yang sangat sukses.

### Konsep Dasar PageRank

PageRank bekerja berdasarkan asumsi bahwa halaman web yang lebih penting kemungkinan besar menerima lebih banyak tautan dari halaman web lainnya. Ide utamanya adalah:

- Setiap tautan ke halaman web berfungsi sebagai "suara" untuk halaman tersebut.
- Tidak semua suara memiliki bobot yang sama. Halaman dengan PageRank tinggi memberikan lebih banyak bobot ke halaman yang mereka tautkan.

### Bagaimana PageRank Bekerja

1. **Model Tautan sebagai Graf**:
   Internet dapat dipandang sebagai graf yang terdiri dari node (halaman web) dan edge (tautan). PageRank memodelkan penjelajah acak yang mengklik tautan dari satu halaman ke halaman lain secara terus menerus.

2. **Distribusi Probabilitas**:
   PageRank memulai dengan memberikan nilai awal yang sama ke setiap halaman. Dalam setiap iterasi, nilai PageRank dari setiap halaman diperbarui berdasarkan PageRank dari halaman yang menautkan ke halaman tersebut.

3. **Iterasi**:
   Proses ini diulang beberapa kali hingga nilai PageRank konvergen (tidak berubah signifikan antara iterasi).

4. **Faktor Damping (Damping Factor)**:
   PageRank memperkenalkan faktor damping untuk mensimulasikan kemungkinan bahwa seorang penjelajah akan berhenti mengikuti tautan dan mulai dari halaman baru secara acak. Biasanya, faktor damping ini diset ke 0.85. Ini berarti 85% dari waktu penjelajah akan mengikuti tautan, dan 15% dari waktu mereka akan melompat ke halaman acak.

### Rumus Matematis

Rumus matematis dari PageRank untuk suatu halaman adalah sebagai berikut:

Algoritma awal

$$ \text{PR}(A) = (1-d) + d \left( \frac{\text{PR}(T_1)}{C(T_1)} + \cdots + \frac{\text{PR}(T_n)}{C(T_n)} \right)$$

Salah satu algoritma lain yang dipublikasikan

$$ PR(A) = \frac{(1-d)}{N} + d \left( \frac{PR(T1)}{C(T1)} + \ldots + \frac{PR(Tn)}{C(Tn)} \right)$$
Dimana:
1. PR(A) adalah Pagerank halaman A
2. PR(T1) adalah Pagerank halaman T1 yang mengacu ke halaman A
3. C(T1) adalah jumlah link keluar (outbound link) pada halaman T1
4. d adalah damping factor yang bisa diberi antara 0 dan 1.
5. N adalah jumlah keseluruhan halaman web (yang terindeks oleh Google)


In [1]:
import numpy as np

data = np.array ([[0,0,1,1/2],[1/3,0,0,0],[1/3,1/2,0,0],[1/3,1/2,0,0]])
v0 = np.array([[0.11],[0.19],[0.5],[0.2]])

v1 = data@v0
v2 = data@v1
v3 = data@v2
v4 = data@v3
v5 = data@v4
v6 = data@v5
v7 = data@v6
v8 = data@v7
v9 = data@v8
v10 = data@v9
print(v1)
print()
print(v2)
print()
print(v3)
print()
print(v3)
print()
print(v4)
print()
print(v5)
print()
print(v6)
print()
print(v7)
print()
print(v8)
print()
print(v9)
print()
print(v10)

[[0.6       ]
 [0.03666667]
 [0.13166667]
 [0.13166667]]

[[0.1975    ]
 [0.2       ]
 [0.21833333]
 [0.21833333]]

[[0.3275    ]
 [0.06583333]
 [0.16583333]
 [0.16583333]]

[[0.3275    ]
 [0.06583333]
 [0.16583333]
 [0.16583333]]

[[0.24875   ]
 [0.10916667]
 [0.14208333]
 [0.14208333]]

[[0.213125  ]
 [0.08291667]
 [0.1375    ]
 [0.1375    ]]

[[0.20625   ]
 [0.07104167]
 [0.1125    ]
 [0.1125    ]]

[[0.16875   ]
 [0.06875   ]
 [0.10427083]
 [0.10427083]]

[[0.15640625]
 [0.05625   ]
 [0.090625  ]
 [0.090625  ]]

[[0.1359375 ]
 [0.05213542]
 [0.08026042]
 [0.08026042]]

[[0.12039063]
 [0.0453125 ]
 [0.07138021]
 [0.07138021]]


### Perkalian Matrik Konvergen

In [2]:
import numpy as np

A = np.array([[0, 0, 1, 1/2],
              [1/3, 0, 0, 0],
              [1/3, 1/2, 0, 1/2],
              [1/3, 1/2, 0, 0]])

v = np.array([[0.50], [0.20], [0.15], [0.15]])

previous_result = v
tolerance = 0.01

for i in range(1, 100):
    result = A @ previous_result
    print(f"(A^{i})v = \n", result)
    if np.all(np.abs(result - previous_result) <= tolerance):
        if np.sqrt(np.sum((result - previous_result) ** 2)) < tolerance:
          print(f"\nPerkalian matriks konvergen pada iterasi ke-{i}.")
          break

    previous_result = result

(A^1)v = 
 [[0.225     ]
 [0.16666667]
 [0.34166667]
 [0.26666667]]
(A^2)v = 
 [[0.475     ]
 [0.075     ]
 [0.29166667]
 [0.15833333]]
(A^3)v = 
 [[0.37083333]
 [0.15833333]
 [0.275     ]
 [0.19583333]]
(A^4)v = 
 [[0.37291667]
 [0.12361111]
 [0.30069444]
 [0.20277778]]
(A^5)v = 
 [[0.40208333]
 [0.12430556]
 [0.2875    ]
 [0.18611111]]
(A^6)v = 
 [[0.38055556]
 [0.13402778]
 [0.28923611]
 [0.19618056]]
(A^7)v = 
 [[0.38732639]
 [0.12685185]
 [0.29195602]
 [0.19386574]]
(A^8)v = 
 [[0.38888889]
 [0.1291088 ]
 [0.28946759]
 [0.19253472]]

Perkalian matriks konvergen pada iterasi ke-8.
