# Determinan Matriks
Determinant adalah suatu nilai skalar yang dapat dihitung dari suatu matriks persegi (matriks dengan jumlah baris dan kolom yang sama). Determinan memiliki beberapa aplikasi penting dalam matematika, termasuk dalam pemecahan sistem persamaan linear, analisis kebalikan matriks, dan teori eigen.


### Rumus Determinan Matriks
1. **Matriks Ordo 2x2:**
   Jika A adalah matriks 2 X 2 dengan elemen:
   $$
   A = \begin{pmatrix}
   a & b \\
   c & d
   \end{pmatrix}
   $$
   Maka determinan det(A) adalah:
   $$
   \text{det}(A) = ad - bc
   $$

2. **Matriks Ordo 3x3:**
   Jika A adalah matriks 3 X 3 dengan elemen:
   $$
   A = \begin{pmatrix}
   a & b & c \\
   d & e & f \\
   g & h & i
   \end{pmatrix}
   $$
   Maka determinan det (A) adalah:
   $$
   \text{det}(A) = a(ei - fh) - b(di - fg) + c(dh - eg)
   $$

3. **Matriks Ordo n X n :**
   Untuk matriks ordo lebih tinggi, determinan dapat dihitung menggunakan ekspansi kofaktor atau metode lain seperti eliminasi Gauss.



### Pengertian Metode Kofaktor
Metode kofaktor adalah salah satu cara untuk menghitung determinan matriks persegi berordo n X n. Metode ini melibatkan penghapusan baris dan kolom untuk menghasilkan matriks minor, kemudian mengalikan elemen-elemen tertentu dengan determinan minor tersebut dan kofaktornya, lalu menjumlahkan hasilnya.

### Langkah-langkah Menghitung Determinan dengan Metode Kofaktor
1. **Pilih baris atau kolom untuk ekspansi kofaktor.** Biasanya, baris atau kolom dengan banyak nol dipilih untuk mengurangi jumlah perhitungan.
2. **Hitung kofaktor** untuk setiap elemen dalam baris atau kolom yang dipilih.
   - **Minor:** Hapus baris dan kolom dari elemen yang dipilih, kemudian hitung determinan dari matriks yang tersisa.
   - **Kofaktor:** Kalikan minor dengan (-1)^{i+j}, di mana i dan j adalah indeks baris dan kolom elemen.
3. **Jumlahkan hasil perkalian** elemen dengan kofaktornya.

### Rumus Ekspansi Kofaktor
Untuk matriks A berordo n X n, determinan det(A) dapat dihitung sebagai:
$$
\text{det}(A) = \sum_{j=1}^{n} (-1)^{i+j} \cdot a_{ij} \cdot \text{det}(M_{ij})
$$

di mana a_{ij} adalah elemen pada baris i dan kolom j , dan M_{ij} adalah minor matriks yang diperoleh dengan menghapus baris i dan kolom j.


### Sifat-sifat determinan
1. jika didalam suatu matrik memiliki 2 baris dengan nilai yang sama maka hasilnya 0
2. jika matrik b 2* matrik a itu bisa dihitung dengan rumus 2^3(ordo)* det a = det b
3. jika matrik b colom pertama 2* matrik a colom pertama itu akan menghasilkan 2*det a

### Mengitung Invers Matrik 5 X 5

In [1]:
import numpy as np

def get_minor(matrix, i, j):
    minor = np.delete(np.delete(matrix, i, axis=0), j, axis=1)
    return minor

def determinant(matrix):
    if matrix.shape[0] == 1:
        return matrix[0, 0]
    if matrix.shape[0] == 2:
        return matrix[0, 0] * matrix[1, 1] - matrix[0, 1] * matrix[1, 0]
    
    det = 0
    for col in range(matrix.shape[1]):
        det += ((-1) ** col) * matrix[0, col] * determinant(get_minor(matrix, 0, col))
    return det

def cofactor_matrix(matrix):
    cofactors = np.zeros(matrix.shape)
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            minor = get_minor(matrix, i, j)
            cofactors[i, j] = ((-1) ** (i + j)) * determinant(minor)
    return cofactors

def inverse(matrix):
    det = determinant(matrix)
    if det == 0:
        raise ValueError("Matrix is singular and cannot be inverted.")
    
    cofactors = cofactor_matrix(matrix)
    adjugate = cofactors.T
    inv_matrix = adjugate / det
    return inv_matrix

# Contoh penggunaan
matrix_5x5 = np.array([
    [2, 5, 3, 7, 1],
    [4, 1, 6, 8, 5],
    [7, 2, 9, 0, 3],
    [5, 3, 8, 2, 4],
    [6, 4, 7, 1, 9]
])

inv_matrix_5x5 = inverse(matrix_5x5)

print("Inverse matrik 5x5:")
print(inv_matrix_5x5)


Inverse matrik 5x5:
[[ 0.15654131  0.05143041  0.53616201 -0.82449373  0.14175506]
 [ 0.16232723 -0.16843459 -0.05593057  0.07521697  0.06075217]
 [-0.13114754 -0.01639344 -0.24590164  0.60655738 -0.16393443]
 [ 0.04982321  0.1067181   0.01253616 -0.08582449 -0.03085824]
 [-0.08003857  0.04146577 -0.14271938  0.05400193  0.12054002]]


### Mengitung Determinan Mtrik 5 x 5 Menggunakan Metode Kofaktor

import numpy as np

def cofactor(matrix, row, col):
    # Menghapus baris 'row' dan kolom 'col' dari matriks
    minor = np.delete(np.delete(matrix, row, axis=0), col, axis=1)
    return ((-1) ** (row + col)) * determinant(minor)

def determinant(matrix):
    # Basis: jika matriks 1x1
    if matrix.shape[0] == 1:
        return matrix[0, 0]
    
    # Basis: jika matriks 2x2
    if matrix.shape[0] == 2:
        return matrix[0, 0] * matrix[1, 1] - matrix[0, 1] * matrix[1, 0]
    
    det = 0
    # Ekspansi kofaktor pada baris pertama
    for col in range(matrix.shape[1]):
        det += matrix[0, col] * cofactor(matrix, 0, col)
    return det

# Contoh penggunaan
matrix_5x5 = np.array([
    [2, 5, 3, 7, 1],
    [4, 1, 6, 8, 5],
    [7, 2, 9, 0, 3],
    [5, 3, 8, 2, 4],
    [6, 4, 7, 1, 9]
])

det_5x5 = determinant(matrix_5x5)

print(f"Determinan menggunakan metode kofaktor: {det_5x5}")


In [2]:
import numpy as np

#fungsi mencari determinan
def det(matriks):
    return np.linalg.det(matriks)

x = np.array([[1,0],[0,1]]) #Determinan matrik identitas adalah 1
c = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(f"#Determinan matrik identitas adalah {det(x)}")
a = np.array([[3,4],[2,1]]) #-5
b = np.array([[6,8],[4,2]]) #-20
print(f"jika matrik b 2* matrik a itu bisa dihitung dengan rumus 2^3(ordo)* det a = {det(b)}")
i = np.array([[6,8],[2,1]])
print('Jika salah satu baris di kali 2 maka hasilnya', det(i).round())
j = np.array([[6,4],[4,1]])
print('Jika colom dikalikan dengan 2 maka hasilnya', det(j).round())
d = np.array([[1,2,1],[3,1,2],[2,1,2]])
print(f"Matrik D {det(d).round()}")
e = np.array([[3,1,2],[1,2,1],[2,1,2]])
print(f'jika Matrik D barisnya di tukar {det(e).round()}')

f = np.array([[1,2,1],[2,4,2],[2,1,2]])
print('determinan matrik f adalah', det(f))
g = np.array([[1,2,1],[2,4,2],[2,4,3]]) 
print('determinan matrik g adalah', det(g))
h = np.array([[6,2,4],[2,4,2],[4,2,4]]) 
print('determinan matrik h adalah', det(h))

k = np.array([[4,1],[2,1]]) 
l = np.array([[7,5],[2,1]])

# Matrik segitiga atas
m = np.array([[1,3,2],[0,2,2],[0,0,1]])
print("ini determinan matrik segitiga atas",det(m))
# Matrik segitiga bawah
n = np.array([[1,0,0],[1,2,0],[1,2,1]])
print("ini determinan matrik segitiga bawah",det(n))


#Determinan matrik identitas adalah 1.0
jika matrik b 2* matrik a itu bisa dihitung dengan rumus 2^3(ordo)* det a = -19.999999999999996
Jika salah satu baris di kali 2 maka hasilnya -10.0
Jika colom dikalikan dengan 2 maka hasilnya -10.0
Matrik D -3.0
jika Matrik D barisnya di tukar 3.0
determinan matrik f adalah 0.0
determinan matrik g adalah 0.0
determinan matrik h adalah 24.000000000000014
ini determinan matrik segitiga atas 2.0
ini determinan matrik segitiga bawah 2.0
