# Aljabar Matrik
Tidak mengerjakan tidak boleh masuk

- Berikan penjelasan tentang apa itu matrik
- Oprasi Matrik (penjumlahan, perkalian, pengurangan, transpose matrik)
- Buat Program untuk mengalikan matrik A dan B



## Definisi Matrik

### 1. Penjelasan tentang matrik :
Matriks adalah sekumpulan bilangan yang disusun berdasarkan baris dan kolom, serta ditempatkan di dalam tanda kurung.
Contoh: 

$$A = \begin{bmatrix} 
3 & 1 & 0 \\ 
5 & 2 & 1 \\ 
0 & 2 & 3
\end{bmatrix}$$

$$c = \begin{bmatrix} 
1 & 2  \\
3 & 4  \\
1 & 0
\end{bmatrix}$$


### 2. Jenis-Jenis Matrik :
Jenis-jenis matrik yaitu Matrik nol, matrik diagonal, matrik skalar, matrik simetris, matrik identitas, matrik segitiga atas, matrik segitiga bawah, matrik transpose.

a. Matrik Nol adalah matrik yang semua elemennya penyusunnya nol:


$$I = \begin{bmatrix}
0 & 0 & 0\\
0 & 0 & 0 \\
0 & 0 & 0
\end{bmatrix}$$

b. Matrik Diagonal adalah suatu matrik yang dimana elemen-elemen diagonalnya mempunyai nilai tidal sama dengan nol dan elemen-elemen selain diagonal bernilai nol:


$$A = \begin{bmatrix}
1 & 0 & 0 \\
0 & 2 & 0 \\
0 & 0 & 3
\end{bmatrix}$$

c. Matrik Skalar adalah matrik yang dimana elemen-elemen diagonalnya bernilai sama dan elemen-elemen selain diagonal bernilai nol:

$$A = \begin{bmatrix}
3 & 0 & 0 \\
0 & 3 & 0 \\
0 & 0 & 3
\end{bmatrix}$$

d. Matriks simetris adalah suatu matrik yang jika elemen-elemen matriks A yang terletak pada baris dan kolom yang sama memiliki nilai yang sama dengan elemen-elemen matriks A yang terletak pada baris dan kolom yang berlawanan: 

$$A = \begin{bmatrix}
3 & 1 & 2 \\
1 & 4 & 0 \\
2 & 0 & 3
\end{bmatrix}$$

e. Matrik Identitas adalah suatu matrik yang elemen-elemen diagonalnya mempunyai nilai 1, sedangkan selain elemen pada diagonal bernilai nol:

$$A = \begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}$$

f. Matrik Segitiga Atas adalah suatu matrik yang elemen-elemennya dibawah diagonal adalah nol:

$$A = \begin{bmatrix}
-2 & 6 & 1 \\
0 & 2 & 3 \\
0 & 0 & -2
\end{bmatrix}$$

g. Matrik Segitiga Bawah adalah suatu matrik yang elemen-elemennya diatas diagonal adalah nol:

$$A = \begin{bmatrix}
-2 & 0 & 0 \\
3 & -2 & 0 
\end{bmatrix}$$

h. Matrik Transpose merupakan matrik yang diperoleh dari memindahkan elemen-elemen baris menjadi kolom atau sebaliknya:\
Selelum Transpose:


$$A = \begin{bmatrix}
1 & 2 & 3 \\ 
4 & 5 & 6
\end{bmatrix}$$

Transpose:

$$A^T = \begin{bmatrix} 
1 & 4  \\
2 & 5  \\
3 & 6
\end{bmatrix}$$

### 3. Penjelasan NumPy
NumPy (Numerical Python) adalah library dalam bahasa pemrograman Python yang digunakan untuk memanipulasi dan meanalisis data numerik. Numpy menyediakan fungsi yang siap pakai untuk memudahkan melakukan perhitungan saintifik seperti matriks, aljabar,dan statistik.

In [1]:
import numpy as np

### 4.  Operasi Matrik
A. Penjumlaan\
Suatu matrik A dan matrik B dapat dijumlahkan apabila matrik A dan Matrik B mempunyai ordo yang sama. Hasil penjumlahannya berupa matrik C dengan ordo yang sama dengan matrik A dan B.
1. Sifat komutatif
Pada sifat ini berlaku A + B = B + A.
2. Sifat asosiatif
Pada sifat ini berlaku (A + B) + C = A +(B + C)
3. Matriks nol
Pada sifat ini berlaku A + 0 = A
4. Jika dijumlahkan dengan lawannya akan menghasilkan matriks nol, yaitu A + (-A) = 0.

In [2]:
a = np.array(([5,8,2],[4,1,-4]))
b = np.array(([9,-4,2],[-2,-4,5]))

print('Ini Matrik a: ')
print(a)
print()
print('Ini Matrik b: ')
print(b)
print()
print('Hasil a + b: ')
print(a+b)

Ini Matrik a: 
[[ 5  8  2]
 [ 4  1 -4]]

Ini Matrik b: 
[[ 9 -4  2]
 [-2 -4  5]]

Hasil a + b: 
[[14  4  4]
 [ 2 -3  1]]


B. Pengurangan\
Suatu matrik A dan matrik B dapat dikurangkan apabila matrik A dan Matrik B mempunyai ordo yang sama. Hasil pengurangannya berupa matrik C dengan ordo yang sama dengan matrik A dan B.

In [3]:
a = np.array(([6,9,3],[-6,4,10]))
b = np.array(([2,9,3],[4,-6,-3]))

print('Ini Matrik a: ')
print(a)
print()
print('Ini Matrik b: ')
print(b)
print()
print('Hasil a - b: ')
print(a-b)

Ini Matrik a: 
[[ 6  9  3]
 [-6  4 10]]

Ini Matrik b: 
[[ 2  9  3]
 [ 4 -6 -3]]

Hasil a - b: 
[[  4   0   0]
 [-10  10  13]]


C. Perklian\
Suatu matrik A dan B dapat dikalikan apabila banyaknya kolom matrik A sama dengan banyaknya baris matrik B. Misal matrik A 4x3 dikalikan dengan matrik B 3x2 maka A dan matrik B dapat dikalikan, dan hasilnya adalah matrik C dengan ordo 4x2.
1. Sifat Asosiatif\
(AB)C = A(BC)
2. Sifat Distributif\
A(B + C) = AB + AC

In [4]:
a = np.array(([1,2,3],[4,5,6],[4,5,6]))
b = np.array(([3,2,1],[-1,-2,-3],[7,5,6]))

hasil = np.dot(a,b)

print('Ini Matrik a: ')
print(a)
print()
print('Ini Matrik b: ')
print(b)
print()
print('Hasil a x b: ')
print(hasil)

Ini Matrik a: 
[[1 2 3]
 [4 5 6]
 [4 5 6]]

Ini Matrik b: 
[[ 3  2  1]
 [-1 -2 -3]
 [ 7  5  6]]

Hasil a x b: 
[[22 13 13]
 [49 28 25]
 [49 28 25]]


D. Perkalian Matrik Tanpa Numpy

In [5]:
math1 = [[1,2,3],
         [4,5,6],
         [4,5,6]]

math2 = [[3,2,1],
         [-1,-2,-3],
         [7,5,6]]


hasil = [[0,0,0],[0,0,0],[0,0,0]]
for x in range(len(math1)): #Perulangan pertama sebanyak panjang math1
    for y in range(len(math2[0])): #Perulangan kedua sebanyak panjang math2 index 0
        for k in range(len(math1[0])): #Perulangan kedua sebanyak panjang math1 index 0
            hasil[x][y]+= math1[x][k]*math2[k][y]

print(math1)
print()
print(math2)
print()
print('Hasil dari perkalian math 1 dan math 2: ')
for k in hasil:
    print(k)

[[1, 2, 3], [4, 5, 6], [4, 5, 6]]

[[3, 2, 1], [-1, -2, -3], [7, 5, 6]]

Hasil dari perkalian math 1 dan math 2: 
[22, 13, 13]
[49, 28, 25]
[49, 28, 25]
